apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 1
  template:
    metadata:
      name: dummy-service
      labels:
        app: dummy-service
    spec:
      containers:
          # My Cool Service
        - name: dummy-service
          image: grepory/dummy
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
