apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 1
  template:
    metadata:
      name: dummy-service
      labels:
        app: dummy-service
    spec:
      containers:
        - name: sensu-agent
          image: us.gcr.io/monitorama-166316/sensu-agent:demo
          imagePullPolicy: Always
          command: ["/opt/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.default.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: dummy
            - name: SENSU_DEREGISTER
              value: "true"
        # My Cool Service
        - name: dummy-service
          image: grepory/dummy
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
