sudo: required
services:
  - docker
language: go
go:
  - 1.8.x
branches:
  only:
  - master
install:
  - "./build.sh deps"
script:
  - "./build.sh"
  - "./build.sh docker"
after_success:
  - "./codecov.sh -t $CODECOV_TOKEN"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag sensuapp/sensu-go:latest sensuapp/sensu-go:master
      docker push sensuapp/sensu-go:master
    fi
env:
  global:
    - secure: hkfmIw8kqHSb1xwJOq9kjtJL5J8VZfVNOjDeQTq6tzUzovqQQzKylENSOs0kmbgRTADOUHRNDt2iVp5/cGtGpFchaIyErJNQVh1l1A1iq1jDgma1UMEoKujn0FYJOurBkZyF3APYJ15n08GoHZdVdUmgWvgeErLyvGJkWhPXOYume2RS0gX5eItB6jdtlj1xiNlCvDc8KpZ6OluMczoe2tNykdX7MwOzhx4uI6uHO5Y4kclBOyJClMWK4aDQfm6SJFyRzEn9nOlGLgCrbJBmc+vF6ge59pWeIaChlp0ukT9M3f074XfiICnRiY9VMofQ7hiWZYfbPApIVX2QthNTuCTJOc4QiI58fZ89+++1lp2GHUG7A2d0M4Uiexc0Io4Or5U+hnb+xIScUzJTWiAIezqCeGjFhTqK/tpUUI0frsBgtpjBTcDTP70vIETardcZD/m/7U+JCLRaF/qhoQgelXyZ2nqsOqqJJayv4WaWHavYTYZhdGkNUdHVV3IrSnkAx2ZClHBV+2nyv1frIv4tGLo0qheQQZ7hrmFkGRO6/zzGB0pKLxF8cJmrM+svt18pW3w56C5c09UAXu5IT0SfYEsPJqXw1aQjxhLplHKJrrstZjVnXU3S+/h20TZS+8mNxxYU0/Ox9MrmETzI4cZ2BiiylMle2gLtqIisQB/qNKY=
    - secure: f+DtaaLy5X0+tbllNOLbWhtVRxkxtm9SUu2DXzmJc4tVV5SKzdD8ewINoPuHmH6XmjhcevFDSTuQEct7gG7d5Pp1HNrtgYmZnrdDFhFXmRUMRwbzUIM4znEl6ej6DsXDvvQ/VZ85b8lH2eSHUk57DRnnrn5Ig96ZNCVy1MZcUZlXS4wx+sgMgsPcPlufkJYZD8pI/jTjLYrurWc96Pb7FsgEsJGbFq5cSQWXoLWgvSs8ZcqaKhR13ikdBhAuXPvASeRTlby+AY7YsDslTb5vgppw5Xt5cfSA0OPlzXA0FgLz60T15CQjq9zQJTndRFHB6cpcMDywF5dmPsec8TnWfr2DziOtQCF8e1+V+gAhL5gaZLj1qvK4Fd/WWBcOlXcdBfTQqRWYXpy81uDwERXzDqkw1wlRqZOmHqR9JdvQgERzrk36AkAWGGOk0Ib3wCobHC2xE4oYW2CNNk/TinwZov5e+rEZEcM4qzlxloHvIjNYTEBbZrhf7nOymTrZCxUtatcZqb76Vd7CJOnoovRAhq1n79GmFKf5vovJWR0RrsW5s2akdB39Rh/uXi2aqfFQ7HCiLGd1dZCvFzWjYjnSVrfmNNZtxBcyBv1sNc/G9hoWqCZPR/7LqL1fQi/xk1CpK92uPl5Z6lNqLoHIAUi8EurcUd3aDuy1SzCZq2w8F5U=
