version: '3'
services:
  sensu-backend1:
    image: sensuapp/sensu-go
    command: sensu-backend start --store-client-url http://127.0.0.1:2379
    hostname: backend1
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
      - "8080:8080"
      - "8081:8081"
  sensu-agent1:
    image: sensuapp/sensu-go
    command: sensu-agent start --backend-url ws://sensu-backend1:8081 --subscriptions test
    hostname: agent1
    restart: always
    links:
      - sensu-backend1:backend1
