#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  name = "github.com/AlecAivazis/survey"
  revision = "c10cbbc78a56bb1f5c62090f4c2813ffcb146a3a"

# https://github.com/Knetic/govaluate/issues/61
[[constraint]]
  name = "github.com/Knetic/govaluate"
  revision = "91facc4ae520fef82c9aee6b6ae720d9ae789131"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/bluele/slack"
  revision = "3b1fffcc45b37a2644a23eb7dc434d4d9f0987ba"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/chzyer/readline"
  version = "1.4.0"

[[constraint]]
  name = "github.com/coreos/pkg"
  version = "3.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/nightlyone/lockfile"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.17.8"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/willf/pad"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/h2non/filetype.v1"
  version = "1.0.3"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "0.13.0"

#
# Lock etcd and some of it's dependencies

[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "76aa7f69357420f1802d4d959ade999e63269942"

[[override]]
  name = "github.com/ugorji/go"
  revision = "708a42d246822952f38190a8d8c4e6b16a0e600c"

[[override]]
  name = "google.golang.org/grpc"
  revision = "d50cf2db166eaff3f2429425758d12205085eb5b"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "fdcb7eab2d6ed4919e83ddcef4f199c161611e1f"

#
# Windows

[[override]]
  name = "github.com/shirou/w32"
  branch = "master"

[[override]]
  name = "github.com/StackExchange/wmi"
  revision = "9f32b5905fd6ce7384093f9d048437e79f7b4d85"

[[override]]
  name = "github.com/go-ole/go-ole"
  revision = "de8695c8edbf8236f30d6e1376e20b198a028d42"
