apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-service
spec:
  replicas: 2
  template:
    metadata:
      name: sensu-agent
      labels:
        app: sensu
    spec:
      containers:
        - name: sensu-agent
          image: us.gcr.io/monitorama-166316/sensu-agent
          command: ["/opt/sensu/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: sensu-backend.default.svc.cluster.local
            - name: SENSU_SUBSCRIPTIONS
              value: dummy
        - name: service
          image: grepory/dummy
          command: /dummy
