apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu-agent
spec:
  replicas: 1
  template:
    metadata:
      name: ubuntu-agent
      labels:
        app: ubuntu-agent
    spec:
      containers:
        - name: sensu-agent
          image: gcr.io/engineering-182923/ubuntu-agent
          command: ["/usr/bin/sensu-agent", "start"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.default.svc.cluster.local:8081
            - name: SENSU_SUBSCRIPTIONS
              value: ubuntu
