version: 2.1

orbs:
  go: circleci/go@1.3.1
  windows: circleci/windows@2.4.0
  go-windows:
    commands:
      install:
        parameters:
          version:
            type: string
            default: 1.15.2
        steps:
          - run:
              working_directory: 'C:\Users\circleci'
              command: >
                curl.exe -fsSLo go.msi
                https://golang.org/dl/go<<parameters.version>>.windows-amd64.msi
          - run:
              working_directory: 'C:\Users\circleci'
              command: >
                msiexec.exe /i go.msi /quiet

executors:
  linux:
    resource_class: large
    docker:
      - image: cimg/go:1.13.15

jobs:
  test:
    parameters:
      executor:
        type: executor
      files:
        type: string
        default: "./..."
      extra_args:
        type: string
        default: ""
    executor: << parameters.executor >>
    parallelism: 1
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"
    steps:
      - checkout
      - go/mod-download-cached
      - run:
          shell: bash -eo pipefail
          command: >
            go test << parameters.extra_args >>
            << parameters.files >>

workflows:
  version: 2
  tests:
    jobs:
      - test:
          name: unit-tests-linux
          executor: linux
          extra_args: -timeout=60s -race
      - test:
          name: unit-tests-windows
          executor: windows/default
          files: "$(go list ./... | grep -v github.com/sensu/sensu-go/backend)"
          extra_args: -timeout=60s
          pre-steps:
            - go-windows/install:
                version: 1.13.15
      - test:
          name: integration-tests-linux
          executor: linux
          extra_args: -timeout=180s -tags=integration
      - test:
          name: integration-tests-windows
          executor: windows/default
          files: "$(go list ./... | grep -v github.com/sensu/sensu-go/backend)"
          extra_args: -timeout=180s -tags=integration
          pre-steps:
            - go-windows/install:
                version: 1.13.15
