version: 2.1

orbs:
  go: circleci/go@1.3.1
  windows: circleci/windows@2.4.0

executors:
  linux:
    docker:
      - image: cimg/go:1.13.15

jobs:
  test:
    parameters:
      executor:
        type: executor
      extra_args:
        type: string
        default: ""
    executor: << parameters.executor >>
    parallelism: 1
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"
    steps:
      - checkout
      - go/mod-download-cached
      - run: go test << parameters.extra_args >> ./...

workflows:
  version: 2
  tests:
    jobs:
      - test:
          name: unit-tests-linux
          executor: linux
          extra_args: -timeout=60s -race
      - test:
          name: unit-tests-windows
          executor: windows/default
          extra_args: -timeout=60s
      - test:
          name: integration-tests-linux
          executor: linux
          extra_args: -timeout=180s -tags=integration
      - test:
          name: integration-tests-windows
          executor: windows/default
          extra_args: -timeout=180s -tags=integration
