version: 2.1

orbs:
  go: circleci/go@1.1.2

executors:
  go:
    resource_class: large
    docker:
      - image: cimg/go:1.13.15
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"

jobs:
  unit:
    executor: go
    parallelism: 4
    environment:
      GOTESTSUM_JUNITFILE: /tmp/results/unit-tests.xml
    steps:
      - checkout
      - go/mod-download-cached
      - run: |
          mkdir -pv $(dirname $GOTESTSUM_JUNITFILE)
          PACKAGES="$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)"
          gotestsum -- -timeout=60s -race $PACKAGES
      - store_test_results:
          path: /tmp/results
  integration:
    executor: go
    parallelism: 4
    environment:
      GOTESTSUM_JUNITFILE: /tmp/results/integration-tests.xml
    steps:
      - checkout
      - go/mod-download-cached
      - run: |
          mkdir -pv $(dirname $GOTESTSUM_JUNITFILE)
          PACKAGES="$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)"
          gotestsum -- -timeout=180s -tags=integration
      - store_test_results:
          path: /tmp/results
      - run: exit $TESTRC

workflows:
  version: 2
  test:
    jobs:
      - unit
      - integration
